


/* Generated by glib-mkenums. Do not edit */

#ifndef __NM_BT_ENUM_TYPES_H__
#define __NM_BT_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType nm_bt_error_get_type (void) G_GNUC_CONST;
#define NM_TYPE_BT_ERROR (nm_bt_error_get_type ())
G_END_DECLS

#endif /* __NM_BT_ENUM_TYPES_H__ */



