


/* Generated by glib-mkenums. Do not edit */

#include "nm-utils-enum-types.h"

#include "nm-connection.h" 
#include "nm-setting.h" 
#include "nm-setting-8021x.h" 
#include "nm-setting-adsl.h" 
#include "nm-setting-bluetooth.h" 
#include "nm-setting-bond.h" 
#include "nm-setting-team.h" 
#include "nm-setting-team-port.h" 
#include "nm-setting-bridge.h" 
#include "nm-setting-bridge-port.h" 
#include "nm-setting-connection.h" 
#include "nm-setting-dcb.h" 
#include "nm-setting-infiniband.h" 
#include "nm-setting-ip4-config.h" 
#include "nm-setting-vlan.h" 
#include "nm-setting-ip6-config.h" 
#include "nm-setting-ppp.h" 
#include "nm-setting-pppoe.h" 
#include "nm-setting-serial.h" 
#include "nm-setting-generic.h" 
#include "nm-setting-gsm.h" 
#include "nm-setting-cdma.h" 
#include "nm-setting-olpc-mesh.h" 
#include "nm-setting-wimax.h" 
#include "nm-setting-wired.h" 
#include "nm-setting-wireless.h" 
#include "nm-setting-wireless-security.h" 
#include "nm-setting-vpn.h" 
#include "nm-utils.h"

GType
nm_connection_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_CONNECTION_ERROR_UNKNOWN, "NM_CONNECTION_ERROR_UNKNOWN", "UnknownError" },
        { NM_CONNECTION_ERROR_CONNECTION_SETTING_NOT_FOUND, "NM_CONNECTION_ERROR_CONNECTION_SETTING_NOT_FOUND", "ConnectionSettingNotFound" },
        { NM_CONNECTION_ERROR_CONNECTION_TYPE_INVALID, "NM_CONNECTION_ERROR_CONNECTION_TYPE_INVALID", "ConnectionTypeInvalid" },
        { NM_CONNECTION_ERROR_SETTING_NOT_FOUND, "NM_CONNECTION_ERROR_SETTING_NOT_FOUND", "SettingNotFound" },
        { NM_CONNECTION_ERROR_INVALID_SETTING, "NM_CONNECTION_ERROR_INVALID_SETTING", "InvalidSetting" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMConnectionError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_ERROR_UNKNOWN, "NM_SETTING_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_ERROR_PROPERTY_NOT_FOUND, "NM_SETTING_ERROR_PROPERTY_NOT_FOUND", "PropertyNotFound" },
        { NM_SETTING_ERROR_PROPERTY_NOT_SECRET, "NM_SETTING_ERROR_PROPERTY_NOT_SECRET", "PropertyNotSecret" },
        { NM_SETTING_ERROR_PROPERTY_TYPE_MISMATCH, "NM_SETTING_ERROR_PROPERTY_TYPE_MISMATCH", "PropertyTypeMismatch" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_secret_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_SECRET_FLAG_NONE, "NM_SETTING_SECRET_FLAG_NONE", "none" },
        { NM_SETTING_SECRET_FLAG_AGENT_OWNED, "NM_SETTING_SECRET_FLAG_AGENT_OWNED", "agent-owned" },
        { NM_SETTING_SECRET_FLAG_NOT_SAVED, "NM_SETTING_SECRET_FLAG_NOT_SAVED", "not-saved" },
        { NM_SETTING_SECRET_FLAG_NOT_REQUIRED, "NM_SETTING_SECRET_FLAG_NOT_REQUIRED", "not-required" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingSecretFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_compare_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_COMPARE_FLAG_EXACT, "NM_SETTING_COMPARE_FLAG_EXACT", "exact" },
        { NM_SETTING_COMPARE_FLAG_FUZZY, "NM_SETTING_COMPARE_FLAG_FUZZY", "fuzzy" },
        { NM_SETTING_COMPARE_FLAG_IGNORE_ID, "NM_SETTING_COMPARE_FLAG_IGNORE_ID", "ignore-id" },
        { NM_SETTING_COMPARE_FLAG_IGNORE_SECRETS, "NM_SETTING_COMPARE_FLAG_IGNORE_SECRETS", "ignore-secrets" },
        { NM_SETTING_COMPARE_FLAG_IGNORE_AGENT_OWNED_SECRETS, "NM_SETTING_COMPARE_FLAG_IGNORE_AGENT_OWNED_SECRETS", "ignore-agent-owned-secrets" },
        { NM_SETTING_COMPARE_FLAG_IGNORE_NOT_SAVED_SECRETS, "NM_SETTING_COMPARE_FLAG_IGNORE_NOT_SAVED_SECRETS", "ignore-not-saved-secrets" },
        { NM_SETTING_COMPARE_FLAG_DIFF_RESULT_WITH_DEFAULT, "NM_SETTING_COMPARE_FLAG_DIFF_RESULT_WITH_DEFAULT", "diff-result-with-default" },
        { NM_SETTING_COMPARE_FLAG_DIFF_RESULT_NO_DEFAULT, "NM_SETTING_COMPARE_FLAG_DIFF_RESULT_NO_DEFAULT", "diff-result-no-default" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingCompareFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_hash_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_HASH_FLAG_ALL, "NM_SETTING_HASH_FLAG_ALL", "all" },
        { NM_SETTING_HASH_FLAG_NO_SECRETS, "NM_SETTING_HASH_FLAG_NO_SECRETS", "no-secrets" },
        { NM_SETTING_HASH_FLAG_ONLY_SECRETS, "NM_SETTING_HASH_FLAG_ONLY_SECRETS", "only-secrets" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingHashFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_diff_result_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_DIFF_RESULT_UNKNOWN, "NM_SETTING_DIFF_RESULT_UNKNOWN", "unknown" },
        { NM_SETTING_DIFF_RESULT_IN_A, "NM_SETTING_DIFF_RESULT_IN_A", "in-a" },
        { NM_SETTING_DIFF_RESULT_IN_B, "NM_SETTING_DIFF_RESULT_IN_B", "in-b" },
        { NM_SETTING_DIFF_RESULT_IN_A_DEFAULT, "NM_SETTING_DIFF_RESULT_IN_A_DEFAULT", "in-a-default" },
        { NM_SETTING_DIFF_RESULT_IN_B_DEFAULT, "NM_SETTING_DIFF_RESULT_IN_B_DEFAULT", "in-b-default" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingDiffResult"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_802_1x_ck_format_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_802_1X_CK_FORMAT_UNKNOWN, "NM_SETTING_802_1X_CK_FORMAT_UNKNOWN", "unknown" },
        { NM_SETTING_802_1X_CK_FORMAT_X509, "NM_SETTING_802_1X_CK_FORMAT_X509", "x509" },
        { NM_SETTING_802_1X_CK_FORMAT_RAW_KEY, "NM_SETTING_802_1X_CK_FORMAT_RAW_KEY", "raw-key" },
        { NM_SETTING_802_1X_CK_FORMAT_PKCS12, "NM_SETTING_802_1X_CK_FORMAT_PKCS12", "pkcs12" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSetting8021xCKFormat"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_802_1x_ck_scheme_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_802_1X_CK_SCHEME_UNKNOWN, "NM_SETTING_802_1X_CK_SCHEME_UNKNOWN", "unknown" },
        { NM_SETTING_802_1X_CK_SCHEME_BLOB, "NM_SETTING_802_1X_CK_SCHEME_BLOB", "blob" },
        { NM_SETTING_802_1X_CK_SCHEME_PATH, "NM_SETTING_802_1X_CK_SCHEME_PATH", "path" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSetting8021xCKScheme"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_802_1x_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_802_1X_ERROR_UNKNOWN, "NM_SETTING_802_1X_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_802_1X_ERROR_INVALID_PROPERTY, "NM_SETTING_802_1X_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_802_1X_ERROR_MISSING_PROPERTY, "NM_SETTING_802_1X_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSetting8021xError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_adsl_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_ADSL_ERROR_UNKNOWN, "NM_SETTING_ADSL_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_ADSL_ERROR_INVALID_PROPERTY, "NM_SETTING_ADSL_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_ADSL_ERROR_MISSING_PROPERTY, "NM_SETTING_ADSL_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingAdslError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_bluetooth_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_BLUETOOTH_ERROR_UNKNOWN, "NM_SETTING_BLUETOOTH_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_BLUETOOTH_ERROR_INVALID_PROPERTY, "NM_SETTING_BLUETOOTH_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_BLUETOOTH_ERROR_MISSING_PROPERTY, "NM_SETTING_BLUETOOTH_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_BLUETOOTH_ERROR_TYPE_SETTING_NOT_FOUND, "NM_SETTING_BLUETOOTH_ERROR_TYPE_SETTING_NOT_FOUND", "TypeSettingNotFound" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingBluetoothError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_bond_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_BOND_ERROR_UNKNOWN, "NM_SETTING_BOND_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_BOND_ERROR_INVALID_PROPERTY, "NM_SETTING_BOND_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_BOND_ERROR_MISSING_PROPERTY, "NM_SETTING_BOND_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_BOND_ERROR_INVALID_OPTION, "NM_SETTING_BOND_ERROR_INVALID_OPTION", "InvalidOption" },
        { NM_SETTING_BOND_ERROR_MISSING_OPTION, "NM_SETTING_BOND_ERROR_MISSING_OPTION", "MissingOption" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingBondError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_team_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_TEAM_ERROR_UNKNOWN, "NM_SETTING_TEAM_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_TEAM_ERROR_INVALID_PROPERTY, "NM_SETTING_TEAM_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_TEAM_ERROR_MISSING_PROPERTY, "NM_SETTING_TEAM_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingTeamError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_team_port_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_TEAM_PORT_ERROR_UNKNOWN, "NM_SETTING_TEAM_PORT_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_TEAM_PORT_ERROR_INVALID_PROPERTY, "NM_SETTING_TEAM_PORT_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_TEAM_PORT_ERROR_MISSING_PROPERTY, "NM_SETTING_TEAM_PORT_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingTeamPortError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_bridge_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_BRIDGE_ERROR_UNKNOWN, "NM_SETTING_BRIDGE_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_BRIDGE_ERROR_INVALID_PROPERTY, "NM_SETTING_BRIDGE_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_BRIDGE_ERROR_MISSING_PROPERTY, "NM_SETTING_BRIDGE_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingBridgeError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_bridge_port_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_BRIDGE_PORT_ERROR_UNKNOWN, "NM_SETTING_BRIDGE_PORT_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_BRIDGE_PORT_ERROR_INVALID_PROPERTY, "NM_SETTING_BRIDGE_PORT_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_BRIDGE_PORT_ERROR_MISSING_PROPERTY, "NM_SETTING_BRIDGE_PORT_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingBridgePortError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_connection_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_CONNECTION_ERROR_UNKNOWN, "NM_SETTING_CONNECTION_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_CONNECTION_ERROR_INVALID_PROPERTY, "NM_SETTING_CONNECTION_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_CONNECTION_ERROR_MISSING_PROPERTY, "NM_SETTING_CONNECTION_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_CONNECTION_ERROR_TYPE_SETTING_NOT_FOUND, "NM_SETTING_CONNECTION_ERROR_TYPE_SETTING_NOT_FOUND", "TypeSettingNotFound" },
        { NM_SETTING_CONNECTION_ERROR_IP_CONFIG_NOT_ALLOWED, "NM_SETTING_CONNECTION_ERROR_IP_CONFIG_NOT_ALLOWED", "IpConfigNotAllowed" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingConnectionError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_dcb_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_DCB_ERROR_UNKNOWN, "NM_SETTING_DCB_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_DCB_ERROR_INVALID_PROPERTY, "NM_SETTING_DCB_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_DCB_ERROR_MISSING_PROPERTY, "NM_SETTING_DCB_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingDcbError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_dcb_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_DCB_FLAG_NONE, "NM_SETTING_DCB_FLAG_NONE", "none" },
        { NM_SETTING_DCB_FLAG_ENABLE, "NM_SETTING_DCB_FLAG_ENABLE", "enable" },
        { NM_SETTING_DCB_FLAG_ADVERTISE, "NM_SETTING_DCB_FLAG_ADVERTISE", "advertise" },
        { NM_SETTING_DCB_FLAG_WILLING, "NM_SETTING_DCB_FLAG_WILLING", "willing" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingDcbFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_infiniband_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_INFINIBAND_ERROR_UNKNOWN, "NM_SETTING_INFINIBAND_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_INFINIBAND_ERROR_INVALID_PROPERTY, "NM_SETTING_INFINIBAND_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_INFINIBAND_ERROR_MISSING_PROPERTY, "NM_SETTING_INFINIBAND_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingInfinibandError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_ip4_config_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_IP4_CONFIG_ERROR_UNKNOWN, "NM_SETTING_IP4_CONFIG_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_IP4_CONFIG_ERROR_INVALID_PROPERTY, "NM_SETTING_IP4_CONFIG_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_IP4_CONFIG_ERROR_MISSING_PROPERTY, "NM_SETTING_IP4_CONFIG_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_IP4_CONFIG_ERROR_NOT_ALLOWED_FOR_METHOD, "NM_SETTING_IP4_CONFIG_ERROR_NOT_ALLOWED_FOR_METHOD", "NotAllowedForMethod" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingIP4ConfigError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_vlan_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_VLAN_ERROR_UNKNOWN, "NM_SETTING_VLAN_ERROR_UNKNOWN", "Unknown" },
        { NM_SETTING_VLAN_ERROR_INVALID_PROPERTY, "NM_SETTING_VLAN_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_VLAN_ERROR_MISSING_PROPERTY, "NM_SETTING_VLAN_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_VLAN_ERROR_INVALID_PARENT, "NM_SETTING_VLAN_ERROR_INVALID_PARENT", "InvalidParent" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingVlanError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_vlan_priority_map_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_VLAN_INGRESS_MAP, "NM_VLAN_INGRESS_MAP", "ingress-map" },
        { NM_VLAN_EGRESS_MAP, "NM_VLAN_EGRESS_MAP", "egress-map" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMVlanPriorityMap"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_vlan_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_VLAN_FLAG_REORDER_HEADERS, "NM_VLAN_FLAG_REORDER_HEADERS", "reorder-headers" },
        { NM_VLAN_FLAG_GVRP, "NM_VLAN_FLAG_GVRP", "gvrp" },
        { NM_VLAN_FLAG_LOOSE_BINDING, "NM_VLAN_FLAG_LOOSE_BINDING", "loose-binding" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMVlanFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_ip6_config_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_IP6_CONFIG_ERROR_UNKNOWN, "NM_SETTING_IP6_CONFIG_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_IP6_CONFIG_ERROR_INVALID_PROPERTY, "NM_SETTING_IP6_CONFIG_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_IP6_CONFIG_ERROR_MISSING_PROPERTY, "NM_SETTING_IP6_CONFIG_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_IP6_CONFIG_ERROR_NOT_ALLOWED_FOR_METHOD, "NM_SETTING_IP6_CONFIG_ERROR_NOT_ALLOWED_FOR_METHOD", "NotAllowedForMethod" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingIP6ConfigError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_ip6_config_privacy_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_IP6_CONFIG_PRIVACY_UNKNOWN, "NM_SETTING_IP6_CONFIG_PRIVACY_UNKNOWN", "unknown" },
        { NM_SETTING_IP6_CONFIG_PRIVACY_DISABLED, "NM_SETTING_IP6_CONFIG_PRIVACY_DISABLED", "disabled" },
        { NM_SETTING_IP6_CONFIG_PRIVACY_PREFER_PUBLIC_ADDR, "NM_SETTING_IP6_CONFIG_PRIVACY_PREFER_PUBLIC_ADDR", "prefer-public-addr" },
        { NM_SETTING_IP6_CONFIG_PRIVACY_PREFER_TEMP_ADDR, "NM_SETTING_IP6_CONFIG_PRIVACY_PREFER_TEMP_ADDR", "prefer-temp-addr" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingIP6ConfigPrivacy"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_ppp_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_PPP_ERROR_UNKNOWN, "NM_SETTING_PPP_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_PPP_ERROR_INVALID_PROPERTY, "NM_SETTING_PPP_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_PPP_ERROR_MISSING_PROPERTY, "NM_SETTING_PPP_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_PPP_ERROR_REQUIRE_MPPE_NOT_ALLOWED, "NM_SETTING_PPP_ERROR_REQUIRE_MPPE_NOT_ALLOWED", "RequireMPPENotAllowed" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingPPPError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_pppoe_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_PPPOE_ERROR_UNKNOWN, "NM_SETTING_PPPOE_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_PPPOE_ERROR_INVALID_PROPERTY, "NM_SETTING_PPPOE_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_PPPOE_ERROR_MISSING_PROPERTY, "NM_SETTING_PPPOE_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_PPPOE_ERROR_MISSING_PPP_SETTING, "NM_SETTING_PPPOE_ERROR_MISSING_PPP_SETTING", "MissingPPPSetting" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingPPPOEError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_serial_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_SERIAL_ERROR_UNKNOWN, "NM_SETTING_SERIAL_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_SERIAL_ERROR_INVALID_PROPERTY, "NM_SETTING_SERIAL_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_SERIAL_ERROR_MISSING_PROPERTY, "NM_SETTING_SERIAL_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_SERIAL_ERROR_MISSING_PPP_SETTING, "NM_SETTING_SERIAL_ERROR_MISSING_PPP_SETTING", "MissingPPPSetting" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingSerialError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_generic_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_GENERIC_ERROR_UNKNOWN, "NM_SETTING_GENERIC_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_GENERIC_ERROR_INVALID_PROPERTY, "NM_SETTING_GENERIC_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_GENERIC_ERROR_MISSING_PROPERTY, "NM_SETTING_GENERIC_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingGenericError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_gsm_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_GSM_ERROR_UNKNOWN, "NM_SETTING_GSM_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_GSM_ERROR_INVALID_PROPERTY, "NM_SETTING_GSM_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_GSM_ERROR_MISSING_PROPERTY, "NM_SETTING_GSM_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_GSM_ERROR_MISSING_SERIAL_SETTING, "NM_SETTING_GSM_ERROR_MISSING_SERIAL_SETTING", "MissingSerialSetting" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingGsmError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_gsm_network_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_GSM_NETWORK_TYPE_ANY, "NM_SETTING_GSM_NETWORK_TYPE_ANY", "any" },
        { NM_SETTING_GSM_NETWORK_TYPE_UMTS_HSPA, "NM_SETTING_GSM_NETWORK_TYPE_UMTS_HSPA", "umts-hspa" },
        { NM_SETTING_GSM_NETWORK_TYPE_GPRS_EDGE, "NM_SETTING_GSM_NETWORK_TYPE_GPRS_EDGE", "gprs-edge" },
        { NM_SETTING_GSM_NETWORK_TYPE_PREFER_UMTS_HSPA, "NM_SETTING_GSM_NETWORK_TYPE_PREFER_UMTS_HSPA", "prefer-umts-hspa" },
        { NM_SETTING_GSM_NETWORK_TYPE_PREFER_GPRS_EDGE, "NM_SETTING_GSM_NETWORK_TYPE_PREFER_GPRS_EDGE", "prefer-gprs-edge" },
        { NM_SETTING_GSM_NETWORK_TYPE_PREFER_4G, "NM_SETTING_GSM_NETWORK_TYPE_PREFER_4G", "prefer-4g" },
        { NM_SETTING_GSM_NETWORK_TYPE_4G, "NM_SETTING_GSM_NETWORK_TYPE_4G", "4g" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingGsmNetworkType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_gsm_network_band_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_GSM_BAND_UNKNOWN, "NM_SETTING_GSM_BAND_UNKNOWN", "unknown" },
        { NM_SETTING_GSM_BAND_ANY, "NM_SETTING_GSM_BAND_ANY", "any" },
        { NM_SETTING_GSM_BAND_EGSM, "NM_SETTING_GSM_BAND_EGSM", "egsm" },
        { NM_SETTING_GSM_BAND_DCS, "NM_SETTING_GSM_BAND_DCS", "dcs" },
        { NM_SETTING_GSM_BAND_PCS, "NM_SETTING_GSM_BAND_PCS", "pcs" },
        { NM_SETTING_GSM_BAND_G850, "NM_SETTING_GSM_BAND_G850", "g850" },
        { NM_SETTING_GSM_BAND_U2100, "NM_SETTING_GSM_BAND_U2100", "u2100" },
        { NM_SETTING_GSM_BAND_U1800, "NM_SETTING_GSM_BAND_U1800", "u1800" },
        { NM_SETTING_GSM_BAND_U17IV, "NM_SETTING_GSM_BAND_U17IV", "u17iv" },
        { NM_SETTING_GSM_BAND_U800, "NM_SETTING_GSM_BAND_U800", "u800" },
        { NM_SETTING_GSM_BAND_U850, "NM_SETTING_GSM_BAND_U850", "u850" },
        { NM_SETTING_GSM_BAND_U900, "NM_SETTING_GSM_BAND_U900", "u900" },
        { NM_SETTING_GSM_BAND_U17IX, "NM_SETTING_GSM_BAND_U17IX", "u17ix" },
        { NM_SETTING_GSM_BAND_U1900, "NM_SETTING_GSM_BAND_U1900", "u1900" },
        { NM_SETTING_GSM_BAND_U2600, "NM_SETTING_GSM_BAND_U2600", "u2600" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingGsmNetworkBand"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_cdma_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_CDMA_ERROR_UNKNOWN, "NM_SETTING_CDMA_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_CDMA_ERROR_INVALID_PROPERTY, "NM_SETTING_CDMA_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_CDMA_ERROR_MISSING_PROPERTY, "NM_SETTING_CDMA_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_CDMA_ERROR_MISSING_SERIAL_SETTING, "NM_SETTING_CDMA_ERROR_MISSING_SERIAL_SETTING", "MissingSerialSetting" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingCdmaError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_olpc_mesh_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_OLPC_MESH_ERROR_UNKNOWN, "NM_SETTING_OLPC_MESH_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_OLPC_MESH_ERROR_INVALID_PROPERTY, "NM_SETTING_OLPC_MESH_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_OLPC_MESH_ERROR_MISSING_PROPERTY, "NM_SETTING_OLPC_MESH_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingOlpcMeshError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_wimax_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_WIMAX_ERROR_UNKNOWN, "NM_SETTING_WIMAX_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_WIMAX_ERROR_INVALID_PROPERTY, "NM_SETTING_WIMAX_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_WIMAX_ERROR_MISSING_PROPERTY, "NM_SETTING_WIMAX_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingWimaxError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_wired_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_WIRED_ERROR_UNKNOWN, "NM_SETTING_WIRED_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_WIRED_ERROR_INVALID_PROPERTY, "NM_SETTING_WIRED_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_WIRED_ERROR_MISSING_PROPERTY, "NM_SETTING_WIRED_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingWiredError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_wireless_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_WIRELESS_ERROR_UNKNOWN, "NM_SETTING_WIRELESS_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_WIRELESS_ERROR_INVALID_PROPERTY, "NM_SETTING_WIRELESS_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_WIRELESS_ERROR_MISSING_PROPERTY, "NM_SETTING_WIRELESS_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_WIRELESS_ERROR_MISSING_SECURITY_SETTING, "NM_SETTING_WIRELESS_ERROR_MISSING_SECURITY_SETTING", "MissingSecuritySetting" },
        { NM_SETTING_WIRELESS_ERROR_CHANNEL_REQUIRES_BAND, "NM_SETTING_WIRELESS_ERROR_CHANNEL_REQUIRES_BAND", "ChannelRequiresBand" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingWirelessError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_wireless_security_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_WIRELESS_SECURITY_ERROR_UNKNOWN, "NM_SETTING_WIRELESS_SECURITY_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_INVALID_PROPERTY, "NM_SETTING_WIRELESS_SECURITY_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_MISSING_PROPERTY, "NM_SETTING_WIRELESS_SECURITY_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_MISSING_802_1X_SETTING, "NM_SETTING_WIRELESS_SECURITY_ERROR_MISSING_802_1X_SETTING", "Missing8021xSetting" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_LEAP_REQUIRES_802_1X, "NM_SETTING_WIRELESS_SECURITY_ERROR_LEAP_REQUIRES_802_1X", "LEAPRequires8021x" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_LEAP_REQUIRES_USERNAME, "NM_SETTING_WIRELESS_SECURITY_ERROR_LEAP_REQUIRES_USERNAME", "LEAPRequiresUsername" },
        { NM_SETTING_WIRELESS_SECURITY_ERROR_SHARED_KEY_REQUIRES_WEP, "NM_SETTING_WIRELESS_SECURITY_ERROR_SHARED_KEY_REQUIRES_WEP", "SharedKeyRequiresWEP" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingWirelessSecurityError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_wep_key_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_WEP_KEY_TYPE_UNKNOWN, "NM_WEP_KEY_TYPE_UNKNOWN", "unknown" },
        { NM_WEP_KEY_TYPE_KEY, "NM_WEP_KEY_TYPE_KEY", "key" },
        { NM_WEP_KEY_TYPE_PASSPHRASE, "NM_WEP_KEY_TYPE_PASSPHRASE", "passphrase" },
        { NM_WEP_KEY_TYPE_LAST, "NM_WEP_KEY_TYPE_LAST", "last" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMWepKeyType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_setting_vpn_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NM_SETTING_VPN_ERROR_UNKNOWN, "NM_SETTING_VPN_ERROR_UNKNOWN", "UnknownError" },
        { NM_SETTING_VPN_ERROR_INVALID_PROPERTY, "NM_SETTING_VPN_ERROR_INVALID_PROPERTY", "InvalidProperty" },
        { NM_SETTING_VPN_ERROR_MISSING_PROPERTY, "NM_SETTING_VPN_ERROR_MISSING_PROPERTY", "MissingProperty" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMSettingVpnError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
nm_utils_security_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { NMU_SEC_INVALID, "NMU_SEC_INVALID", "invalid" },
        { NMU_SEC_NONE, "NMU_SEC_NONE", "none" },
        { NMU_SEC_STATIC_WEP, "NMU_SEC_STATIC_WEP", "static-wep" },
        { NMU_SEC_LEAP, "NMU_SEC_LEAP", "leap" },
        { NMU_SEC_DYNAMIC_WEP, "NMU_SEC_DYNAMIC_WEP", "dynamic-wep" },
        { NMU_SEC_WPA_PSK, "NMU_SEC_WPA_PSK", "wpa-psk" },
        { NMU_SEC_WPA_ENTERPRISE, "NMU_SEC_WPA_ENTERPRISE", "wpa-enterprise" },
        { NMU_SEC_WPA2_PSK, "NMU_SEC_WPA2_PSK", "wpa2-psk" },
        { NMU_SEC_WPA2_ENTERPRISE, "NMU_SEC_WPA2_ENTERPRISE", "wpa2-enterprise" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("NMUtilsSecurityType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}



