


/* Generated by glib-mkenums. Do not edit */

#ifndef __NM_ADSL_ENUM_TYPES_H__
#define __NM_ADSL_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
G_END_DECLS

#endif /* __NM_ADSL_ENUM_TYPES_H__ */



