/* Generated by dbus-binding-tool; do not edit! */


#ifndef __dbus_glib_marshal_nm_active_connection_MARSHAL_H__
#define __dbus_glib_marshal_nm_active_connection_MARSHAL_H__

#include	<glib-object.h>

G_BEGIN_DECLS

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  g_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     g_value_get_schar (v)
#define g_marshal_value_peek_uchar(v)    g_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      g_value_get_int (v)
#define g_marshal_value_peek_uint(v)     g_value_get_uint (v)
#define g_marshal_value_peek_long(v)     g_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    g_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    g_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   g_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     g_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    g_value_get_flags (v)
#define g_marshal_value_peek_float(v)    g_value_get_float (v)
#define g_marshal_value_peek_double(v)   g_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) g_value_get_string (v)
#define g_marshal_value_peek_param(v)    g_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    g_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  g_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   g_value_get_object (v)
#define g_marshal_value_peek_variant(v)  g_value_get_variant (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses GValues directly, which is UNSUPPORTED API.
 *          Do not access GValues directly in your code. Instead, use the
 *          g_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_variant(v)  (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */


G_END_DECLS

#endif /* __dbus_glib_marshal_nm_active_connection_MARSHAL_H__ */

#include <dbus/dbus-glib.h>
static const DBusGMethodInfo dbus_glib_nm_active_connection_methods[] = {
};

const DBusGObjectInfo dbus_glib_nm_active_connection_object_info = {  1,
  dbus_glib_nm_active_connection_methods,
  0,
"\0",
"org.freedesktop.NetworkManager.Connection.Active\0PropertiesChanged\0\0",
"org.freedesktop.NetworkManager.Connection.Active\0Connection\0connection\0read\0org.freedesktop.NetworkManager.Connection.Active\0SpecificObject\0specific_object\0read\0org.freedesktop.NetworkManager.Connection.Active\0Id\0id\0read\0org.freedesktop.NetworkManager.Connection.Active\0Uuid\0uuid\0read\0org.freedesktop.NetworkManager.Connection.Active\0Type\0type\0read\0org.freedesktop.NetworkManager.Connection.Active\0Devices\0devices\0read\0org.freedesktop.NetworkManager.Connection.Active\0State\0state\0read\0org.freedesktop.NetworkManager.Connection.Active\0Default\0default\0read\0org.freedesktop.NetworkManager.Connection.Active\0Ip4Config\0ip4_config\0read\0org.freedesktop.NetworkManager.Connection.Active\0Dhcp4Config\0dhcp4_config\0read\0org.freedesktop.NetworkManager.Connection.Active\0Default6\0default6\0read\0org.freedesktop.NetworkManager.Connection.Active\0Ip6Config\0ip6_config\0read\0org.freedesktop.NetworkManager.Connection.Active\0Dhcp6Config\0dhcp6_config\0read\0org.freedesktop.NetworkManager.Connection.Active\0Vpn\0vpn\0read\0org.freedesktop.NetworkManager.Connection.Active\0Master\0master\0read\0\0"
};

